name: Erlang CI

on: [push]

env:
    ERLANG_VERSION: 21.3.8.12

jobs:
    build:
        runs-on: ubuntu-latest

        container: erlang:21.3.8.12

        steps:
        - uses: actions/checkout@v2

        - name: Restore dialyzer cache
          uses: actions/cache@v1
          with:
            path: ~/.cache/rebar3
            key: dialyzer-${{ env.ERLANG_VERSION }}

        - name: Lint
          run: rebar3 lint

        - name: Compile
          run: rebar3 compile

        - name: Xref
          run: rebar3 xref

        - name: Dialyze
          run: rebar3 dialyzer

        - name: Run tests
          run: rebar3 do eunit, proper

        - name: Clean up
          run: find ~/.cache/rebar3/* ! -name 'rebar3_${{ env.ERLANG_VERSION }}_plt' ! -name '.' -exec rm -rf {} +
