name: Erlang CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        container:
          image: erlang:21.3.8.12
        steps:
        - uses: actions/checkout@v2
        - name: Compile
          run: rebar3 compile
        - name: Xref
          run: rebar3 xref
        - name: Dialyze
          run: rebar3 dialyzer
        - name: Run tests
          run: rebar3 do eunit, ct
